# Generated by Django 4.0.4 on 2022-06-20 07:27

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("notification_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databasenotification",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="databasenotification",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="databasenotification",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
