# Generated by Django 4.1.2 on 2023-03-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasenotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="databasenotification",
            index=models.Index(fields=["type"], name="notificatio_type_3c12e3_idx"),
        ),
        migrations.AddIndex(
            model_name="databasenotification",
            index=models.Index(fields=["read"], name="notificatio_read_01651a_idx"),
        ),
    ]
