# Generated by Django 4.0.4 on 2022-06-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_system", "0002_alter_databasenotification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databasenotification",
            options={"ordering": ["-created"]},
        ),
    ]
