# Generated by Django 4.1 on 2022-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification_system", "0003_alter_databasenotification_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="databasenotification",
            index=models.Index(fields=["type"], name="notificatio_type_3c12e3_idx"),
        ),
        migrations.AddIndex(
            model_name="databasenotification",
            index=models.Index(fields=["read"], name="notificatio_read_01651a_idx"),
        ),
    ]
