# Generated by Django 4.0.3 on 2022-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_options_agent_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalagent",
            name="id",
            field=models.BigIntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
    ]
