# Generated by Django 4.1.2 on 2022-11-16 19:11

from django.db import migrations

def migrate_address_data(apps, schema_editor):
    Agent = apps.get_model('agents', 'Agent')

    for agent in Agent.objects.all():
        address = agent.address
        agent.address1 = address.address1
        agent.address2 = address.address2
        agent.city = address.city
        agent.state = address.state
        agent.zip_code = address.zip_code
        agent.save()

class Migration(migrations.Migration):

    dependencies = [
        (
            "agents",
            "0008_agent_address1_agent_address2_agent_city_agent_state_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_address_data)
    ]
