# Generated by Django 4.1.2 on 2023-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
