# Generated by Django 4.0.3 on 2022-03-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_historicaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="activated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="activated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
