# Generated by Django 4.0.3 on 2022-03-21 14:13

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_historicaluser_activated_at_user_activated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, null=True, upload_to="uploads/profile-pictures/"
            ),
        ),
    ]
