# Generated by Django 4.0.3 on 2022-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_historicaluser_is_active_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="new_email",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="new_email",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
