# Generated by Django 4.0.4 on 2022-05-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='password',
        ),
    ]
