# Generated by Django 4.1 on 2022-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_historicaluser_phone_number_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["activated_at"], name="users_user_activat_843d23_idx"
            ),
        ),
    ]
