# Generated by Django 4.0.4 on 2022-06-18 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_databasenotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatabaseNotification",
        ),
    ]
