# Generated by Django 4.1.2 on 2023-02-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_databasenotification"),
        ("farms", "0010_remove_agent_address_remove_historicalagent_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
