# Generated by Django 4.1.2 on 2023-01-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_delete_databasenotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
