# Generated by Django 4.1.2 on 2023-03-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalfarm",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(fields=["name"], name="farms_farm_name_b646b2_idx"),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(fields=["email"], name="farms_farm_email_46efd1_idx"),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["phone_number"], name="farms_farm_phone_n_402305_idx"
            ),
        ),
    ]
