# Generated by Django 4.1 on 2022-10-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_alter_agent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalagent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical agent",
                "verbose_name_plural": "historical agents",
            },
        ),
        migrations.AlterField(
            model_name="historicalagent",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
