# Generated by Django 4.1 on 2022-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_alter_historicalagent_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["phone_number"], name="agents_agen_phone_n_6da118_idx"
            ),
        ),
    ]
