# Generated by Django 4.1.2 on 2022-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0007_agent_agents_agen_phone_n_6da118_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="address1",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="address2",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="zip_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="address1",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="address2",
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="zip_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
