# Generated by Django 4.1.2 on 2022-11-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0009_auto_20221116_1911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="address",
        ),
        migrations.RemoveField(
            model_name="historicalagent",
            name="address",
        ),
    ]
