# Generated by Django 4.1.2 on 2023-01-30 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0010_remove_agent_address_remove_historicalagent_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Agent",
            new_name="Farm",
        ),
        migrations.RenameModel(
            old_name="HistoricalAgent",
            new_name="HistoricalFarm",
        ),
        migrations.AlterModelOptions(
            name="historicalfarm",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical farm",
                "verbose_name_plural": "historical farms",
            },
        ),
        migrations.RenameIndex(
            model_name="farm",
            new_name="agents_farm_name_28d5f4_idx",
            old_name="agents_agen_name_26b7c8_idx",
        ),
        migrations.RenameIndex(
            model_name="farm",
            new_name="agents_farm_email_4f6512_idx",
            old_name="agents_agen_email_c3a8fb_idx",
        ),
        migrations.RenameIndex(
            model_name="farm",
            new_name="agents_farm_phone_n_bae812_idx",
            old_name="agents_agen_phone_n_6da118_idx",
        ),
    ]