FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements requirements
RUN pip install -r requirements/prod.txt

COPY . .

EXPOSE $PORT

# Production Server
CMD newrelic-admin run-program gunicorn --bind 0.0.0.0:$PORT --access-logfile - {{ cookiecutter.project_slug }}.wsgi:application
