FROM python:3.10
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY ./requirements requirements
RUN pip install -r requirements/prod.txt

# Install gettext in order to use Django's Translation system for internationalization support
RUN apt-get update && apt-get install gettext -y

COPY . .

EXPOSE $PORT

# Production Server
CMD ["/app/entrypoint.sh"]
